#ifndef CGNS_IO_H_
#define CGNS_IO_H_

#include <stdio.h>
#include <stdlib.h>
#include <petsc.h>

#include "pcgnslib.h"
#include "mpi.h"

typedef struct {
  double   x;
  double   y;
} Vector2D;

/**
 * Write mesh grid to a cgns file.
 */
PetscErrorCode CGNSMeshWrite(DM dm, Vec * fullmesh);

/**
 * Read the existing grid file and add cell centered
 * flow solution to it.
 */
PetscErrorCode CGNSCellSolWrite(DM dm, Vec * globalSol);

/**
 * Write mesh and solution at the same time.
 * Temperory function because bugs in CGNSCellSolWrite.
 */
PetscErrorCode DMDACgnsOut2D(DM dmMesh, Vec *fullmesh, DM dmCell, Vec *Sol, char *filename); 

/**
 * Write mesh and solution out.
 * Write arrays generated by FE solution
 */
PetscErrorCode CgnsArrayOutput(DM dmMesh, Vec * fullmesh, 
                               double * ux, 
                               double * uy,
                               int cxs, int cxm, int cys, int cym,
                               char * filename);


#endif
